Numpy is a general-purpose array-processing package
It stands for Numerical Python,is a fundamental library for numerical and scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [1]:
# import numpy as alias np

import numpy as np


Difference between list and an array
NumPy arrays use less memory and run faster for numerical tasks.
Lists are more flexible but not optimized for mathematical operations.

Create an array using numpy
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function

In [2]:
import numpy as np

l = [1,2,3,4]
arr = np.array([1,2,3,4])

print(l)
print(type(l))
print(arr)
print(type(arr))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# 0-d  array(scalar)
arr_0d = np.array(23) # a single number --like a point
print(arr_0d)
type(arr_0d)

23


numpy.ndarray

In [4]:
# 1-d array -- A simple list of numbers --- like a row
arr_1d = np.array([1,2,3,4])
print("1 D array: ",arr_1d)

1 D array:  [1 2 3 4]


In [5]:
# 2- d array --- a table with rows and columns
arr_2d = np.array([[1,2], [3,4]])
print(arr_2d)

[[1 2]
 [3 4]]


In [6]:
# 3d array
arr_3d = np.array([[[1,2,3],[4,5,6], [9,8,7]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [9 8 7]]]


Array inspection -- These functions help you inspect, understand, and convert arrays easily. Very useful for debugging and data preprocessing in NumPy.

In [7]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# shape -- tells you the structure
print(arr.shape)

(2, 3)


In [9]:
print(arr.size)  #total no of elements

6


In [10]:
print(arr.min())
print(arr.max())

1
6


In [11]:
# dtype ---- data type of array elements
print(arr.dtype)

int64


In [12]:
# change data type
arr_float = arr.astype(float)
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
# ndim --- tells about the dimension of an array
#arr1 = np.array([[[1,2,3,4],[3,4,5,6], [9,8,7,6]]])
arr = np.array([[1,2,3], [4,5,6]])

#arr_ndim = arr1.ndim
ar_ndim = arr.ndim
#arr_ndim
ar_ndim

2

Why Numpy?
Memory - Numpy data structures take up less space.
Performance -they have a need for speed and are faster than lists.
Functionality - Scipy and Numpy have optimized functions such as linear algebra operations built in.

In [14]:
# memory
import numpy as np
import sys

# declaring a list of 10 elements
S =[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print("Size of each element of list in bytes:", sys.getsizeof(S))
print("Size of the whole list in bytes:", sys.getsizeof(S) * len(S))

# declaring a Numpy array of 10 elements
D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Size of each element of the Numpy array in bytes: ", D.itemsize)
print("Size of the whole Numpy array in bytes: ", D.size * D.itemsize)

Size of each element of list in bytes: 136
Size of the whole list in bytes: 1360
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  80


Array Manipulation
Array manipulation refers to modifying the structure or elements of an array, such as:

Reshaping - np.reshape(array, shape)

Flattening - np.flatten(array)

Transposing - np.flatten(array)

Joining or splitting

Adding or removing elements

Function	Purpose
reshape()	Change shape
flatten()	Convert to 1D
transpose()	Swap axes
concatenate()	Join arrays
split()	Divide array
stack()	Stack arrays along new axis


In [15]:
# 1 d array
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) #---> 30
print(arr[1:4]) # ---[20 30 40]

30
[20 30 40]


In [16]:
# 2 d array
arr2d = np.array([[1,2,3],#---0
                  [4,5,6],#---1
                  [7,8,9]])#---2
print(arr2d[1, 2])
print(arr2d[0:2, 1:])

6
[[2 3]
 [5 6]]


In [17]:
# 3d array
arr3d = np.array([[[1, 2], [3,4]],# bock==0
                  [[5,6],[7,8]]]) # block==1
print(arr3d)
print(arr3d[1, 0, 1]) #=== 6 (block1, row 0, col 1)
print(arr3d[:, 1, :])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6
[[3 4]
 [7 8]]


In [18]:
#flatten()-- converts multidimensional array to 1 d array
a = np.array([[1,2], [3,4]])
print(a)
print(a.flatten())

[[1 2]
 [3 4]]
[1 2 3 4]


In [19]:
# transpose-- swaps rows with columns
a = np.array([[1,2], [3,4]])
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [20]:
import numpy as np
# concatenate --used to join arrays
a = np.array([[1,2]])
b = np.array([[3,4]])
print(a)
print(b)
print("--------------")
c= np.concatenate((a,b), axis = 1)
d = np.concatenate((a,b), axis = 0)
print(c)
print(d)
print(np.shape(c))
print(np.shape(d))

[[1 2]]
[[3 4]]
--------------
[[1 2 3 4]]
[[1 2]
 [3 4]]
(1, 4)
(2, 2)


In [21]:
a = np.array([1,2])
b = np.array([3,4])
np.stack((a,b), axis = 0) # vertical stack
# print(z)
# print(np.shape(z))

array([[1, 2],
       [3, 4]])

In [22]:
np.stack((a,b), axis = 1) # horizontal stack

array([[1, 3],
       [2, 4]])

In [23]:
# split
a = np.array([1,2,3,4,5,6])
print(np.split(a,2))

[array([1, 2, 3]), array([4, 5, 6])]
